DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS genres;

CREATE TABLE artists (
  id SERIAL8 PRIMARY KEY
);

CREATE TABLE albums (
  id SERIAL8 PRIMARY KEY
);

CREATE TABLE genres (
  id SERIAL8 PRIMARY KEY
);

CREATE TABLE stock (
  id SERIAL8 PRIMARY KEY
);
